"""initial schema

Revision ID: c5d5a4e0c08b
Revises: 
Create Date: 2025-08-16 09:21:18.060310

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'c5d5a4e0c08b'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('scoring_rules',
    sa.Column('scoring_id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=64), nullable=False),
    sa.Column('pass_yd', sa.Numeric(precision=6, scale=3), nullable=False),
    sa.Column('pass_td', sa.Numeric(precision=6, scale=3), nullable=False),
    sa.Column('pass_int', sa.Numeric(precision=6, scale=3), nullable=False),
    sa.Column('rush_yd', sa.Numeric(precision=6, scale=3), nullable=False),
    sa.Column('rush_td', sa.Numeric(precision=6, scale=3), nullable=False),
    sa.Column('rec_yd', sa.Numeric(precision=6, scale=3), nullable=False),
    sa.Column('rec_td', sa.Numeric(precision=6, scale=3), nullable=False),
    sa.Column('reception', sa.Numeric(precision=6, scale=3), nullable=False),
    sa.Column('fumble_lost', sa.Numeric(precision=6, scale=3), nullable=False),
    sa.PrimaryKeyConstraint('scoring_id'),
    sa.UniqueConstraint('name')
    )
    op.create_table('seasons',
    sa.Column('season_id', sa.Integer(), nullable=False),
    sa.Column('year', sa.Integer(), nullable=False),
    sa.Column('pre_w1_start', sa.Date(), nullable=True),
    sa.Column('reg_w1_start', sa.Date(), nullable=True),
    sa.PrimaryKeyConstraint('season_id')
    )
    op.create_index(op.f('ix_seasons_year'), 'seasons', ['year'], unique=True)
    op.create_table('teams',
    sa.Column('team_id', sa.Integer(), nullable=False),
    sa.Column('abbr', sa.String(length=8), nullable=False),
    sa.Column('name', sa.String(length=128), nullable=False),
    sa.Column('logo_url', sa.Text(), nullable=True),
    sa.PrimaryKeyConstraint('team_id')
    )
    op.create_index(op.f('ix_teams_abbr'), 'teams', ['abbr'], unique=True)
    op.create_table('games',
    sa.Column('game_id', sa.Integer(), nullable=False),
    sa.Column('event_id', sa.String(length=32), nullable=False),
    sa.Column('season_id', sa.Integer(), nullable=False),
    sa.Column('overall_week', sa.Integer(), nullable=False),
    sa.Column('kickoff', sa.DateTime(timezone=True), nullable=True),
    sa.Column('status', sa.String(length=16), nullable=True),
    sa.Column('venue', sa.String(length=128), nullable=True),
    sa.ForeignKeyConstraint(['season_id'], ['seasons.season_id'], ),
    sa.PrimaryKeyConstraint('game_id')
    )
    op.create_index(op.f('ix_games_event_id'), 'games', ['event_id'], unique=True)
    op.create_table('players',
    sa.Column('player_id', sa.Integer(), nullable=False),
    sa.Column('ext_id', sa.String(length=64), nullable=False),
    sa.Column('name', sa.String(length=128), nullable=False),
    sa.Column('position', sa.String(length=8), nullable=True),
    sa.Column('team_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['team_id'], ['teams.team_id'], ),
    sa.PrimaryKeyConstraint('player_id')
    )
    op.create_index(op.f('ix_players_ext_id'), 'players', ['ext_id'], unique=True)
    op.create_index(op.f('ix_players_name'), 'players', ['name'], unique=False)
    op.create_table('game_teams',
    sa.Column('game_id', sa.Integer(), nullable=False),
    sa.Column('team_id', sa.Integer(), nullable=False),
    sa.Column('home_away', sa.String(length=4), nullable=False),
    sa.Column('score', sa.Integer(), nullable=True),
    sa.CheckConstraint("home_away IN ('home','away')"),
    sa.ForeignKeyConstraint(['game_id'], ['games.game_id'], ),
    sa.ForeignKeyConstraint(['team_id'], ['teams.team_id'], ),
    sa.PrimaryKeyConstraint('game_id', 'team_id'),
    sa.UniqueConstraint('game_id', 'home_away', name='uq_game_homeaway')
    )
    op.create_table('player_stats',
    sa.Column('game_id', sa.Integer(), nullable=False),
    sa.Column('player_id', sa.Integer(), nullable=False),
    sa.Column('team_id', sa.Integer(), nullable=False),
    sa.Column('position', sa.String(length=8), nullable=True),
    sa.Column('pass_yd', sa.Integer(), nullable=False),
    sa.Column('pass_td', sa.Integer(), nullable=False),
    sa.Column('pass_int', sa.Integer(), nullable=False),
    sa.Column('rush_yd', sa.Integer(), nullable=False),
    sa.Column('rush_td', sa.Integer(), nullable=False),
    sa.Column('rec_yd', sa.Integer(), nullable=False),
    sa.Column('rec_td', sa.Integer(), nullable=False),
    sa.Column('receptions', sa.Integer(), nullable=False),
    sa.Column('fumbles_lost', sa.Integer(), nullable=False),
    sa.Column('fantasy_points', sa.Numeric(precision=6, scale=2), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['game_id'], ['games.game_id'], ),
    sa.ForeignKeyConstraint(['player_id'], ['players.player_id'], ),
    sa.ForeignKeyConstraint(['team_id'], ['teams.team_id'], ),
    sa.PrimaryKeyConstraint('game_id', 'player_id')
    )
    op.create_index(op.f('ix_player_stats_team_id'), 'player_stats', ['team_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_player_stats_team_id'), table_name='player_stats')
    op.drop_table('player_stats')
    op.drop_table('game_teams')
    op.drop_index(op.f('ix_players_name'), table_name='players')
    op.drop_index(op.f('ix_players_ext_id'), table_name='players')
    op.drop_table('players')
    op.drop_index(op.f('ix_games_event_id'), table_name='games')
    op.drop_table('games')
    op.drop_index(op.f('ix_teams_abbr'), table_name='teams')
    op.drop_table('teams')
    op.drop_index(op.f('ix_seasons_year'), table_name='seasons')
    op.drop_table('seasons')
    op.drop_table('scoring_rules')
    # ### end Alembic commands ###
